### ISSUE TITLE
Richiesta DB vuoto

### ISSUE THREAD

**Issue by ivanomiscali** [ComuneDiGenova/emergenze-pcge#4]
Buongiorno, ho installato il vostro prodotto e ho visto nella documentazione che sarà prevista a breve una copia del db.
Avete delle previsioni su quando sarà disponibile? Altrimenti non riesco ad approfondire le funzionalità.
Grazie Ivano

**Comment by RobiFag** [comment]
Buongiorno, la copia del DB è stata rilasciata ed è ora disponibile su questa repository.
